fragment Reactions on Reactable {
  reactionGroups {
    content
    reactors {
      totalCount
    }
  }
}

fragment CoreCommentFields on Comment {
  author {
    login
  }
  authorAssociation
  createdAt
  ...Reactions
  body
}

fragment Labels on Labelable {
  labels(first: 10) {
    nodes {
      name
    }
  }
}

fragment CrossReferencedEventFields on CrossReferencedEvent {
  referencedAt
  willCloseTarget
  source {
    __typename
    ... on Issue {
      ...CoreIssueFields
    }
    ... on PullRequest {
      ...CorePRFields
    }
  }
}

fragment CoreCommitFields on Commit {
  committedDate
  oid
  message
  authors(first: 10) {
    nodes {
      user {
        login
        name
      }
    }
  }
}

fragment CoreIssueFields on Issue {
  ...CoreCommentFields
  ...Labels
  url
  title
  milestone {
    title
    description
  }
  isPinned
  state
  stateReason
}

fragment FullIssueFields on Issue {
  ...CoreIssueFields
  timelineItems(last: 20, itemTypes: [CROSS_REFERENCED_EVENT, ISSUE_COMMENT]) {
    nodes {
      __typename
      ... on Comment {
        ...CoreCommentFields
      }
      ... on CrossReferencedEvent {
        ...CrossReferencedEventFields
      }
    }
  }
}

fragment CorePRFields on PullRequest {
  ...CoreCommentFields
  ...Labels
  url
  title
  milestone {
    title
    description
  }
  prState: state
}

fragment FullPRFields on PullRequest {
  ...CorePRFields
  timelineItems(
    last: 20
    itemTypes: [
      CROSS_REFERENCED_EVENT
      ISSUE_COMMENT
      PULL_REQUEST_REVIEW
      PULL_REQUEST_COMMIT
    ]
  ) {
    nodes {
      __typename
      ... on Comment {
        ...CoreCommentFields
      }
      ... on CrossReferencedEvent {
        ...CrossReferencedEventFields
      }
      ... on PullRequestReview {
        ...CoreCommentFields
        state
        comments(first: 10) {
          nodes {
            ...CoreCommentFields
            diffHunk
          }
        }
      }
      ... on PullRequestCommit {
        commit {
          ...CoreCommitFields
        }
      }
    }
  }
  closingIssuesReferences(first: 5) {
    nodes {
      ...CoreIssueFields
    }
  }
}

query (
  $owner: String!
  $name: String!
  $since: GitTimestamp!
  $until: GitTimestamp!
  $openPullsQuery: String!
  $mergedPullsQuery: String!
  $openIssuesQuery: String!
  $closedIssuesQuery: String!
  $discussionsQuery: String!
  $count: Int = 8
) {
  repository(owner: $owner, name: $name) {
    nameWithOwner
    description
    defaultBranchRef {
      target {
        ... on Commit {
          history(first: 100, since: $since, until: $until) {
            nodes {
              parents {
                totalCount
              }
              ...CoreCommitFields
            }
          }
        }
      }
    }

    # FIXME: Only get releases between $since and $until
    releases(first: 100, orderBy: { field: CREATED_AT, direction: DESC }) {
      nodes {
        name
        description
        publishedAt
        url
        author {
          login
        }
        ...Reactions
        tagCommit {
          ...CoreCommitFields
        }
      }
    }
  }

  # Get the pulls merged between $since and $until
  mergedPulls: search(type: ISSUE, query: $mergedPullsQuery, first: $count) {
    nodes {
      ... on PullRequest {
        ...FullPRFields
        mergeCommit {
          oid
        }
      }
    }
  }

  # Get the open pulls updated between $since and $until
  openPulls: search(type: ISSUE, query: $openPullsQuery, first: $count) {
    nodes {
      ... on PullRequest {
        ...FullPRFields
      }
    }
  }

  # Get the issues closed between $since and $until
  closedIssues: search(type: ISSUE, query: $closedIssuesQuery, first: $count) {
    nodes {
      ...FullIssueFields
    }
  }

  # Get the open issues updated between $since and $until
  openIssues: search(type: ISSUE, query: $openIssuesQuery, first: $count) {
    nodes {
      ...FullIssueFields
    }
  }

  # Get the discussions updated between $since and $until
  discussions: search(
    type: DISCUSSION
    query: $discussionsQuery
    first: $count
  ) {
    nodes {
      ... on Discussion {
        ...CoreCommentFields
        ...Labels
        url
        title
        comments(first: 10) {
          nodes {
            replies(first: 10) {
              nodes {
                ...CoreCommentFields
              }
            }
            ...CoreCommentFields
          }
        }
      }
    }
  }
}
