steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/pi-registry/pi-dev-web-image",
        ".",
        "--build-arg",
        "COMMIT_SHA=$COMMIT_SHA",
      ]
    env:
      - "DOCKER_BUILDKIT=1"

images:
  - "us-central1-docker.pkg.dev/${PROJECT_ID}/pi-registry/pi-dev-web-image"
